[package]
name = "tailwind-importer"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Use tailwind across your rust project"
repository = "https://github.com/BrettMayson/tailwind-importer"

[dependencies]
paste = "1.0.9"
walkdir = "2.3.2"
